### ISSUE TITLE
ngc build fails with outsourced declarations/entryComponents in app.module.ts

### ISSUE THREAD

**Issue by chron0** [driftyco/ionic-starter-super#1]
I've tried to adapt the neat declarations/entryComponents method used in app.module.ts of the app branch. I don't run builds often enough and as this works in ionic serve (dev) mode but it fails during ngc compilation, I just wanted to drop it here as a reminder:

```
> ionic-hello-world@ ionic:build /home/chrono/src/ionic-starter-super
> ionic-app-scripts build

[09:34:46]  ionic-app-scripts 0.0.44 
[09:34:46]  build prod started ... 
[09:34:46]  clean started ... 
[09:34:46]  clean finished in 8 ms 
[09:34:46]  copy started ... 
[09:34:46]  ngc started ... 
[09:34:46]  copy finished in 59 ms 
[09:34:49]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider 
            replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in 
            /home/chrono/src/ionic-starter-super/.tmp/app/app.module.ts, resolving symbol AppModule in 
            /home/chrono/src/ionic-starter-super/.tmp/app/app.module.ts 
[09:34:49]  ngc failed 
[09:34:49]  ionic-app-script task: "build" 
[09:34:49]  Error: Error 
```

**Comment by mlynch** [comment]
Thanks, haven't tested with ngc yet so I might have to adjust that approach

**Comment by mlynch** [comment]
Fixed that in my recent updates and found a nice balance between centralizing things in pages/providers.ts and having them in the module.

**Comment by chron0** [comment]
I've tried it yesterday and while it worked in dev, a run with --prod ngc failed again. Will have to check if there were more commits after that which have fixed it.

**Comment by chron0** [comment]
Nope, still won't work for prod here. The main diffeence is: I am using pipes, so my entrycomponents and declarations obviously diverge. I've tried numerous ways of merging pipes into pages and having ngc accept the return of the declaration, but to no avail:

```
/*******************************************************************************
 * pages
 */

export const pages: any = [
  GovernessApp,
  AboutPage,
  AppliancesPage,
  AppliancesHelp,
  ApplianceDetailPage,
  AddPluginModal,
  EditPluginModal,
  Dashboard,
  DashboardHelp,
  HelpPage,
  LogsPage,
  SettingsPage,
  SettingsHelp,
  TasksPage,
  TasksHelp,
  TaskDetailPage,
];

/*******************************************************************************
 * pipes
 */

export const pipes: any = [
  TemperaturePipe,
];

/*******************************************************************************
 * entryComponents
 */

export function entryComponents(): any {
  return pages;
}

/*******************************************************************************
 * declarations
 */

export function declarations(): any {
  let test: any = pages;
  test.push(pipes[0]);
  return test;
}

/*******************************************************************************
 * providers
 */

export function providers(): any {
  return [
    HashID,
    ColorPickerService,
    StorageService,
    ConfigService,
    ApplianceService,
    PlatformService,
    PluginService,
    StatusService,
    TaskService,
    WebSocketService,
    // Enable Ionic's storage engine
    { provide: Storage, useFactory: provideStorage },
    // Enable Ionic's runtime error handling during development
    { provide: ErrorHandler, useClass: IonicErrorHandler },
  ];
}

/*******************************************************************************
 * imports
 */

export let imports: any = [
  ChartModule,
  ColorPickerModule,
  TranslateModule.forRoot({
    provide: TranslateLoader,
    useFactory: (createTranslateLoader),
    deps: [ Http ],
  }),
  IonicModule.forRoot(GovernessApp, {
    mode: 'md',
    menuType: 'overlay',
    activator: 'ripple',
  }),
];

/*******************************************************************************
 *
 *    NgModule
 *
 */

@NgModule({
  declarations: declarations(),
  imports: imports,
  bootstrap: [ IonicApp ],
  entryComponents: entryComponents(),
  providers: providers(),
})
```

**Comment by ryaa** [comment]
I had the same issue and to be able to create prod build i had to move declarations and entryComponents to be inline in NgModule.

```
@NgModule({
  declarations: [

    // PAGES
    AboutPage,
    MyApp,
    CardsPage,
    ContentPage,
    LoginPage,
    .......

    // COMPONENTS
    ......

    // DIRECTIVES
    .....

    // PIPES
    .....

  ],
  imports: [
    IonicModule.forRoot(MyApp),
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    }),
    FormsModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    
    // PAGES
    .....

    // COMPONENTS
    .....

  ],
  providers: providers()
})
```
